### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by koh-jx**
- Add SetTask, PurgeTask tests (incl undo)
- Add undo tests for EditTask, DoneTask, PurgeTask
- Add 1 more test case to Edit (person) to account for change in a contact's name

TODO:
- Undo for more commands
- Redo test

### CODE REVIEW

**Comment by koh-jx** [comment]
Why is codecov not here wtf

**Comment by mingyi456** [comment]
Add another commit and see if codecov posts? This is weird though
image

**Comment by koh-jx** [comment]
> Add another commit and see if codecov posts? This is weird though image

oo okk

**Review by yeppog — APPROVED** [review]
lgtm

**Pull request merged**
